export const PERMISSIONS = [
  { id: 'view_dashboard', label: 'عرض لوحة التحكم' },
  { id: 'view_pos', label: 'عرض نقطة البيع' },
  { id: 'apply_discounts', label: 'تطبيق الخصومات' },
  { id: 'void_items', label: 'إلغاء عناصر' },
  { id: 'view_returns', label: 'عرض المرتجعات' },
  { id: 'process_returns', label: 'معالجة المرتجعات' },
  { id: 'view_inventory', label: 'عرض المخزون' },
  { id: 'add_product', label: 'إضافة منتج' },
  { id: 'edit_product', label: 'تعديل منتج' },
  { id: 'delete_product', label: 'حذف منتج' },
  { id: 'manage_categories', label: 'إدارة الأقسام' },
  { id: 'view_stocktaking', label: 'عرض الجرد' },
  { id: 'manage_stocktaking', label: 'إدارة الجرد' },
  { id: 'view_purchases', label: 'عرض المشتريات' },
  { id: 'add_purchase', label: 'إضافة مشتريات' },
  { id: 'edit_purchase', label: 'تعديل مشتريات' },
  { id: 'delete_purchase', label: 'حذف مشتريات' },
  { id: 'view_customers', label: 'عرض العملاء' },
  { id: 'add_customer', label: 'إضافة عميل' },
  { id: 'edit_customer', label: 'تعديل عميل' },
  { id: 'delete_customer', label: 'حذف عميل' },
  { id: 'view_suppliers', label: 'عرض الموردين' },
  { id: 'add_supplier', label: 'إضافة مورد' },
  { id: 'edit_supplier', label: 'تعديل مورد' },
  { id: 'delete_supplier', label: 'حذف مورد' },
  { id: 'view_employees', label: 'عرض الموظفين' },
  { id: 'add_employee', label: 'إضافة موظف' },
  { id: 'edit_employee', label: 'تعديل موظف' },
  { id: 'delete_employee', label: 'حذف موظف' },
  { id: 'view_attendance', label: 'عرض الحضور' },
  { id: 'manage_attendance', label: 'إدارة الحضور' },
  { id: 'view_payroll', label: 'عرض الرواتب' },
  { id: 'manage_payroll', label: 'إدارة الرواتب' },
  { id: 'view_offers', label: 'عرض العروض' },
  { id: 'manage_offers', label: 'إدارة العروض' },
  { id: 'view_branches', label: 'عرض الفروع' },
  { id: 'manage_branches', label: 'إدارة الفروع' },
  { id: 'view_mobile_sales', label: 'عرض تطبيق المناديب' },
  { id: 'view_shifts', label: 'عرض الورديات' },
  { id: 'manage_shifts', label: 'إدارة الورديات' },
  { id: 'view_expenses', label: 'عرض المصروفات' },
  { id: 'add_expense', label: 'إضافة مصروف' },
  { id: 'edit_expense', label: 'تعديل مصروف' },
  { id: 'delete_expense', label: 'حذف مصروف' },
  { id: 'view_reports', label: 'عرض التقارير' },
  { id: 'manage_settings', label: 'إدارة الإعدادات' },
];
