export const PERMISSIONS = [
  { id: 'can_view_dashboard', label: 'عرض لوحة التحكم' },
  { id: 'can_view_pos', label: 'عرض نقطة البيع' },
  { id: 'can_view_returns', label: 'عرض المرتجعات' },
  { id: 'can_view_inventory', label: 'عرض المخزون' },
  { id: 'can_edit_inventory', label: 'تعديل المخزون' },
  { id: 'can_view_purchases', label: 'عرض المشتريات' },
  { id: 'can_view_customers', label: 'عرض العملاء' },
  { id: 'can_view_suppliers', label: 'عرض الموردين' },
  { id: 'can_manage_employees', label: 'إدارة الموظفين' },
  { id: 'can_view_attendance', label: 'عرض الحضور' },
  { id: 'can_view_payroll', label: 'عرض الرواتب' },
  { id: 'can_view_offers', label: 'عرض العروض' },
  { id: 'can_view_branches', label: 'عرض الفروع' },
  { id: 'can_view_mobile_sales', label: 'عرض تطبيق المناديب' },
  { id: 'can_view_shifts', label: 'عرض الورديات' },
  { id: 'can_view_expenses', label: 'عرض المصروفات' },
  { id: 'can_view_reports', label: 'عرض التقارير' },
  { id: 'can_manage_settings', label: 'إدارة الإعدادات' },
];
